### ISSUE TITLE
On the question of testing currency

### ISSUE THREAD

**Issue by tianxingjian007** [BitcherryFoundation/blockchain#1]
谢谢

**Comment by tianxingjian007** [comment]
It's useless to send 100 test coins

**Comment by tianxingjian007** [comment]
没上主网 还没映射之前 收取手续费不合理

**Comment by BitCherryChain** [comment]
> The service charge for sending test coins awarded by the test network is unreasonable, which can not make the user experience fully. This kind of service charge can be understood after the main network goes online. It is suggested that the total amount of test coins awarded can be limited according to the number of users every day, until they are collected on a first come first served basis every day

**Comment by BitCherryChain** [comment]
> > The service charge for sending test coins awarded by the test network is unreasonable, which can not make the user experience fully. This kind of service charge can be understood after the main network goes online. It is suggested that the total amount of test coins awarded can be limited according to the number of users every day, until they are collected on a first come first served basis every day

**Comment by BitCherryChain** [comment]
> 没上主网 还没映射之前 收取手续费不合理

您好，目前在测试环节，测试币仅用于测试，实际并不产生手续费

**Comment by BitCherryChain** [comment]
> The service charge for sending test coins awarded by the test network is unreasonable, which can not make the user experience fully. This kind of service charge can be understood after the main network goes online. It is suggested that the total amount of test coins awarded can be limited according to the number of users every day, until they are collected on a first come first served basis every day

OK, thank you for your feedback, we will give reasonable consideration to your suggestions

**Comment by BitCherryChain** [comment]
> It's useless to send 100 test coins

IS this not enough for testing the Testnet?

**Comment by tianxingjian007** [comment]
期待bitcherry越来越好，成为一个大公链

**Comment by BitCherryChain** [comment]
> 期待bitcherry越来越好，成为一个大公链
谢谢，期待您后期更多地参与bitcherry主网生态建设
